
import { Innertube } from 'youtubei.js';

const DEFAULT_URL = 'https://www.youtube.com/watch?v=DhRoTONcyZE';
const rawUrl = process.argv[2] || DEFAULT_URL;
const videoUrl = rawUrl.replace(/^\\+/, '').replace(/~+$/, '').trim();

const INLINE_COOKIES = `
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814006672	__Secure-3PSID	g.dia000-Qho0AxKLo-iy-BWb2cqUcN2QdRFuq7EEG5xd42JaRLof27oejl4jbrGcQgBdQjtHYwZrQACgYKAQ0SARASFQHGX2Mito8EKU13UAkIo1StV0RKmhoVAUF8yKrew63k4CPQ5-3UcLHj67Xp0076
.youtube.com	TRUE	/	FALSE	1810984898	SIDCC	AKEyXzUQkTmvQ0TqPWdlKuKTZ2lyA2p23yPnneuovxHCeCcH9TKBUuMjBGRCi7xPNkat9vzXDQ
.youtube.com	TRUE	/	FALSE	1814006672	SID	g.a000-Qho0AxKLo-iy-BWb2cqUcN2QdRFuq7EEG5xd42JaRLof27oYsR3MJPBMg4HBLrp37VUngACgYKAWASARASFQHGX2MivDyerlZzR6C8KPkqbyILNRoVAUF8yKoTpNYqZnMxa4Lh31twElrs0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1810984491	__Secure-1PSIDTS	sidts-CjUBhkeRdzsBbHr1CR4R6xdXFKfbNfrSg6SdJE-jNF2QCuApRvnmobzrXAbHVbZRL7jQkrks8xAA
.youtube.com	TRUE	/	TRUE	1779449320	CONSISTENCY	AHzIXrwMzy7FMNLsKP-8to06388XFwoURQ9IptslpDfpnCQx8eBQsdT04QHc2BAqtmfajESWI3oD77RQzxxzJR68ZluFCOSVyiEB9UAABRofpqNJ47CH2sxFGc1wi5O9qk-AQ_aBRDLr4XJhcSND1aJY
.youtube.com	TRUE	/	TRUE	1814006672	SAPISID	HfFxWKW8JThVmJ2I/AP3aeOfM8gAWxZMFY
#HttpOnly_.youtube.com	TRUE	/	TRUE	1810984898	__Secure-1PSIDCC	AKEyXzW-ZymHXwVqbicBx8hkqKkPLq0YfQFiN_e3npIIoAkkrt1f4i37bcafGPl3aBPuq6TJ-g
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814006672	SSID	AC6hHXocjgIj2WM88
.youtube.com	TRUE	/	TRUE	1814006672	__Secure-1PAPISID	HfFxWKW8JThVmJ2I/AP3aeOfM8gAWxZMFY
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814006672	__Secure-1PSID	g.a000-Qho0AxKLo-iy-BWb2cqUcN2QdRFuq7EEG5xd42JaRLof27ooHhmKecSIs59jZzmk8VWXwACgYKAYUSARASFQHGX2MiiUXGyqSGXXwZqnKvqnw2_xoVAUF8yKrgU3jTStv8cS16PtvEsZzh0076
.youtube.com	TRUE	/	TRUE	1814006672	__Secure-3PAPISID	HfFxWKW8JThVmJ2I/AP3aeOfM8gAWxZMFY
#HttpOnly_.youtube.com	TRUE	/	TRUE	1810984898	__Secure-3PSIDCC	AKEyXzWhOgn2GPLTzZDWQb_zmrIHzkS4l5_AYW82gc3n4SxWTvlHmehGUsHE66u0FPXBCCOE
#HttpOnly_.youtube.com	TRUE	/	TRUE	1810984491	__Secure-3PSIDTS	sidts-CjUBhkeRdzsBbHr1CR4R6xdXFKfbNfrSg6SdJE-jNF2QCuApRvnmobzrXAbHVbZRL7jQkrks8xAA
.youtube.com	TRUE	/	FALSE	1814006672	APISID	3DTa4Kii-BFeoJTh/ARErDtehQY6BI44bQ
#HttpOnly_.youtube.com	TRUE	/	FALSE	1814006672	HSID	Ac6c05yjMnEiX_2pN
#HttpOnly_.youtube.com	TRUE	/	TRUE	1814006680	LOGIN_INFO	AFmmF2swRQIhAOsdHsMjFRLim6VQQ5jWfiA2so09-74kw_1kXMD9baVFAiA_TfRYpLhv-ZIiK09N7kGKoH7gq7kl8htJNiyBtpsm9Q:QUQ3MjNmeG5URE91RXdHeXlhSE40VXBUa2pIWDNKNzFpTUpjNUNDcjBxRXBYTmR4VHBsd0x1QmdWUldDX3NvNjlMT2FzajJXZ1ZaWnpld2RBLTQ1bUVyTmZZZTdJT3VaMkNYelVKUV9xSFBORU5aU2lNWUJiQmt5STcybUtxQmdhb3JQdEZOVC1EMWk3NWI1clplTGZEbnQzUmFHVEFBUXJ3
.youtube.com	TRUE	/	TRUE	1814008895	PREF	f4=4000000&tz=UTC
`;

function extractVideoId(url: string): string {
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
  const match = url.match(regExp);
  return (match && match[2].length === 11) ? match[2] : url;
}

function fmtBytes(bytes: number | null | undefined): string {
  if (!bytes) return 'Unknown';
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function fmtDuration(sec: number): string {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = sec % 60;
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  return `${m}:${String(s).padStart(2, '0')}`;
}

async function main() {
  console.log('='.repeat(70));
  console.log('🚀 STANDALONE NATIVE YOUTUBE (YOUTUBEI.JS) DOWNLOAD DIAGNOSTIC');
  console.log('='.repeat(70));
  console.log(`Video URL: ${videoUrl}`);
  console.log(`Loading inline cookies...`);

  let cookieString = '';
  try {
    const lines = INLINE_COOKIES.split(/\r?\n/);
    const cookiePairs: string[] = [];
    const cookieNames: string[] = [];

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const parts = trimmed.split('\t');
      if (parts.length >= 7) {
        const name = parts[5].trim();
        const value = parts[6].trim();
        if (name && value) {
          cookiePairs.push(`${name}=${value}`);
          cookieNames.push(name);
        }
      }
    }
    cookieString = cookiePairs.join('; ');
    console.log(`✅ Loaded & parsed inline cookies! (${cookiePairs.length} cookies found)`);
    console.log(`📋 Cookies detected: ${cookieNames.join(', ')}`);

    // Check for critical YouTube authentication cookies
    const authCookies = ['SID', 'HSID', 'SSID', 'SAPISID', '__Secure-3PSID', 'LOGIN_INFO'];
    const foundAuth = cookieNames.filter(name => authCookies.includes(name));
    const hasSession = foundAuth.length > 0;

    if (!hasSession) {
      console.log('\n' + '='.repeat(70));
      console.log('⚠️ WARNING: NO ACTIVE YOUTUBE LOGIN SESSION DETECTED IN COOKIES!');
      console.log('='.repeat(70));
      console.log('The loaded cookies only contain visitor/guest identifiers:');
      console.log(`- Found visitor cookies: ${cookieNames.filter(n => !authCookies.includes(n)).join(', ') || 'None'}`);
      console.log(`- Missing critical authentication cookies: ${authCookies.join(', ')}`);
      console.log('\nBecause this script is running in a VPS/Datacenter environment (with a flagged IP),');
      console.log('YouTube aggressively blocks guest/visitor sessions with:');
      console.log('  "Sign in to confirm you’re not a bot" (LOGIN_REQUIRED)');
      console.log('='.repeat(70) + '\n');
    } else {
      console.log(`🔐 Logged-in session cookies verified! (Found: ${foundAuth.join(', ')})`);
    }
  } catch (err: any) {
    console.warn(`⚠️ Warning: Could not parse cookies: ${err.message || err}`);
  }

  console.log('='.repeat(70));

  console.log('🔄 Initializing Innertube (youtubei.js) client...');
  const startInit = Date.now();
  const config: any = {};
  if (cookieString) {
    config.cookie = cookieString;
  }
  const youtube = await Innertube.create(config);
  console.log(`✅ Innertube client ready in ${((Date.now() - startInit) / 1000).toFixed(2)}s!`);
  console.log('='.repeat(70));

  console.log('⏳ Fetching video metadata using multiple client probes...');
  const videoId = extractVideoId(videoUrl);
  const clients = ['ANDROID', 'IOS', 'TV', 'MWEB', 'WEB'];
  let info: any = null;
  let successfulClient = '';

  for (const client of clients) {
    console.log(`📡 Probing client: ${client}...`);
    try {
      const startFetch = Date.now();
      const currentInfo = await youtube.getInfo(videoId, client as any);
      const status = currentInfo.playability_status?.status;
      const reason = currentInfo.playability_status?.reason;
      const subreason = (currentInfo.playability_status as any)?.error_screen?.subreason?.text;
      console.log(`   └─ Status: ${status || 'OK'} (${((Date.now() - startFetch) / 1000).toFixed(2)}s)`);

      if (status === 'OK' || !status) {
        info = currentInfo;
        successfulClient = client;
        break;
      } else {
        console.warn(`   ⚠️ Playability warning: "${reason || 'Unknown block'}"`);
        if (subreason) {
          console.warn(`      └─ Subreason: "${subreason}"`);
        }
      }
    } catch (err: any) {
      console.warn(`   ❌ Client probe failed: ${err.message || err}`);
    }
  }

  if (!info) {
    console.error('❌ ERROR: All client probes failed to retrieve playable stream formats!');
    console.error('YouTube requires login or has blocked the IP completely.');
    process.exit(1);
  }

  console.log(`✅ Video info successfully retrieved using client: ${successfulClient}!`);
  console.log('='.repeat(70));

  const basic = info.basic_info;
  console.log(`🎥 Title       : ${basic.title}`);
  console.log(`👤 Uploader    : ${basic.author}`);
  console.log(`⏱ Duration    : ${fmtDuration(basic.duration || 0)}`);
  console.log(`👀 Views       : ${basic.view_count?.toLocaleString()}`);
  console.log(`👍 Likes       : ${basic.like_count || 'N/A'}`);
  console.log(`🖼 Thumbnail   : ${basic.thumbnail?.[0]?.url || 'N/A'}`);
  console.log('='.repeat(70));

  console.log('📊 Available Pre-Merged Muxed Formats (Video + Audio):');
  const muxedFormats = info.streaming_data?.formats || [];
  muxedFormats.forEach((f: any) => {
    const size = f.content_length ? parseInt(f.content_length) : null;
    console.log(`  - Itag: ${f.itag.toString().padEnd(5)} | Res: ${(f.quality_label || f.quality || 'N/A').padEnd(8)} | Type: ${f.mime_type.split(';')[0].padEnd(12)} | Size: ${fmtBytes(size)}`);
  });

  console.log('\n📊 Available Adaptive Audio Formats:');
  const adaptiveFormats = info.streaming_data?.adaptive_formats || [];
  const audioFormats = adaptiveFormats.filter((f: any) => f.mime_type?.startsWith('audio/'));
  audioFormats.forEach((f: any) => {
    const size = f.content_length ? parseInt(f.content_length) : null;
    const bitrate = f.bitrate ? `${Math.round(f.bitrate / 1000)} kbps` : 'N/A';
    console.log(`  - Itag: ${f.itag.toString().padEnd(5)} | Bitrate: ${bitrate.padEnd(10)} | Type: ${f.mime_type.split(';')[0].padEnd(12)} | Size: ${fmtBytes(size)}`);
  });
  console.log('='.repeat(70));

  console.log('⚡ Choosing best Video+Audio format for testing...');
  const bestFormat = info.chooseFormat({ type: 'video+audio', quality: 'best' });
  if (!bestFormat) {
    console.error('❌ Could not find a suitable Video+Audio format!');
    process.exit(1);
  }
  const size = bestFormat.content_length ? parseInt(bestFormat.content_length as any) : null;
  console.log(`👉 Selected Format: Itag ${bestFormat.itag} (${bestFormat.quality_label || bestFormat.quality}), size: ${fmtBytes(size)}`);
  console.log('='.repeat(70));

  console.log('📥 Downloading video stream chunk-by-chunk in-memory...');
  const startDownload = Date.now();
  const stream = await info.download(bestFormat as any);
  const reader = stream.getReader();
  const chunks: Uint8Array[] = [];
  let downloadedBytes = 0;
  const totalBytes = size || 0;
  let lastProgressReport = Date.now();

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    if (value) {
      chunks.push(value);
      downloadedBytes += value.length;
      if (totalBytes > 0) {
        const pct = (downloadedBytes / totalBytes) * 100;
        const now = Date.now();
        if (now - lastProgressReport > 500 || pct >= 100) {
          console.log(`   [Download Progress] ${pct.toFixed(1)}% (${fmtBytes(downloadedBytes)} / ${fmtBytes(totalBytes)})`);
          lastProgressReport = now;
        }
      } else {
        const now = Date.now();
        if (now - lastProgressReport > 500) {
          console.log(`   [Download Progress] Received ${fmtBytes(downloadedBytes)}`);
          lastProgressReport = now;
        }
      }
    }
  }

  const elapsed = ((Date.now() - startDownload) / 1000).toFixed(2);
  const buffer = Buffer.concat(chunks.map(c => Buffer.from(c)));
  console.log('='.repeat(70));
  console.log(`🎉 SUCCESS! Video stream fully downloaded in-memory in ${elapsed}s!`);
  console.log(`📦 Buffer Size : ${fmtBytes(buffer.length)}`);
  console.log('='.repeat(70));
  process.exit(0);
}

main().catch((err) => {
  console.error('Fatal initialization error:', err);
  process.exit(1);
});